---
name: Release Drafter

# yamllint disable-line rule:truthy
on:
  workflow_dispatch:
  push:
    branches:
      - main

permissions: {}

jobs:
  update_release_draft:
    name: ✏️ Draft release
    runs-on: ubuntu-24.04-arm
    permissions:
      contents: write
      pull-requests: read
    steps:
      - name: 🚀 Run Release Drafter
        uses: release-drafter/release-drafter@c2e2804cc59f45f57076a99af580d0fedb697927 # v7.3.0
        with:
          commitish: ${{ github.sha }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
