---
name: Release Drafter

# yamllint disable-line rule:truthy
on:
  workflow_dispatch:
  push:
    branches:
      - main

permissions: {}

jobs:
  update_release_draft:
    name: ✏️ Draft release
    runs-on: ubuntu-24.04-arm
    permissions:
      contents: write
      pull-requests: read
    steps:
      - name: 🚀 Run Release Drafter
        uses: release-drafter/release-drafter@139054aeaa9adc52ab36ddf67437541f039b88e2 # v7.1.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
