name: "test-windows"
on:
  pull_request:
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test-default-version:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - name: Should not be on path
        run: |
          if (!(Get-Command -Name "uv" -ErrorAction SilentlyContinue)) {
            exit 0
          } else {
            exit 1
          }
      - name: Setup uv
        uses: ./
      - run: uv sync
        working-directory: __tests__\fixtures\uv-project
